project:
  type: website
  output-dir: docs
website:
  title: "U.T.M.E. Validity Meta-Analysis"
  navbar:
    left:
      - text: Summary & Results
        href: index.qmd
      - href: methods.qmd
        text: Methods
      - href: search.qmd
        text: Search Results
      - href: study_data.qmd
        text: Study Data
      - href: contribute.qmd
        text: Contribute

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: visual

